version: '2'

services:
  web:
    build: ./.
    links:
      - db
      - redis
    networks: 
      - front
    ports:
      - "8080:8080"
    volumes:
      - scratch_data:/scratch
  db:
    image: mysql:${TAG}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}
    networks: 
      - back
    volumes:
      - scratch_data:/scratch
  redis:
    image: redis:3-alpine
    environment:
      - REDIS_PASS=${REDISPASSWORD}
      - LOGLEVEL=debug
    networks: 
      - back
    links:
      - db:db
    volumes:
      - scratch_data:/scratch

networks:
  front:
#    labels:
#      - "Front end network"
    driver: bridge
  back:
#    labels: 
#      - "Back end network"
    driver: bridge


volumes:
  scratch_data:
    external:
      name: scratch_data
