web:
  #image: exclusivecipher/private
  build: ./.
  links:
    - db
    - redis
  ports:
    - "8080:8080"
db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=testingpasword
redis:
  image: redis:3-alpine
  environment:
    - REDIS_PASS=testingpassword
    - LOGLEVEL=debug
